### ISSUE TITLE
Can't Override Package Config 

### ISSUE THREAD

**Issue by leepowelldev** [TheBnl/silverstripe-cookie-consent#3]
Trying to disable css and javascript through a `app/_config/cookies.yml` file with the following content:

```
---
Name: cookies
---
Broarm\CookieConsent\CookieConsent:
  include_javascript: false
  include_css: false
  create_default_pages: false
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    Analytics:
      local:
        - _ga
        - _gid
```

However, both this config and the one that comes with the package seem to get merged together, with the package config taking priority. This gives me the following:

```
Array
(
    [cookies] => Array
        (
            [Necessary] => Array
                (
                    [local] => Array
                        (
                            [0] => PHPSESSID
                            [1] => CookieConsent
                            [2] => PHPSESSID
                            [3] => CookieConsent
                        )

                )

            [Analytics] => Array
                (
                    [local] => Array
                        (
                            [0] => _ga
                            [1] => _gid
                        )

                )

        )

    [include_javascript] => 1
    [include_css] => 1
    [create_default_pages] => 1
    [extensions] => Array
        (
        )

    [unextendable_classes] => Array
        (
            [0] => SilverStripe\View\ViewableData
            [1] => SilverStripe\Control\RequestHandler
        )

)
```

As you can see the `include_javascript`, `include_css` and `create_default_pages` are being ignored. I also had to change the `XD\CookieConsent\CookieConsent:` in the documentation to `Broarm\CookieConsent\CookieConsent:`.
