### ISSUE TITLE
 Saving cookie prefs fail when more then 3 cookie categories

### ISSUE THREAD

**Issue by andreassp** [TheBnl/silverstripe-cookie-consent#35]
Hi
We use the module in several projects - when using more than 3 cookie categories (f.e. necessary, analytics, social media, video) the "saving" action at the cookie settings page (`CookiePolicyPage`) is behaving strange.
After choosing 3 of 4 categories and submitting, some categories stay active, others get unchecked again and do not get saved. 
I just did a fresh install with SS4.8, it´s the same. 
Any ideas? Thanks!

**Comment by TheBnl** [comment]
Hi Andreassp, sorry for the late response. 
Could you send your yml config?

**Comment by andreassp** [comment]
Hi - here is our yml conf

```
Broarm\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      domainname.com:
        - CookieConsent
        - PHPSESSID
    Analytics:
      Google:
        - _ga
        - _gid
        - _gcl_au
        - _gcl_aw
    SocialMedia:
      facebook:
        - _fbp
        - fr
    Video:
      vimeo:
        - continuous_play_v3
        - player
```
