### ISSUE TITLE
isRequired configurable in CMS?

### ISSUE THREAD

**Issue by silverstripesk** [TheBnl/silverstripe-cookie-consent#5]
Hello,
really nice module, good job!
What do you think about making isRequired CookieGroup configurable in CMS. I need 2 separate groups, but both necessary...

**Comment by TheBnl** [comment]
Hi Silverstripesk,

Thanks for the suggestion! 
Making the required groups configurable is a good idea, i am considering the following syntax:
```yml
Broarm\CookieConsent\CookieConsent:
  required_groups:
    - Necessary
    - OtherGroup
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
```
Everything under the `cookies` setting is looped over and considered as a CookieGroup or Cookie so setting the required flag there is not possible unfortunately.

**Comment by silverstripesk** [comment]
Hi,
sounds good for me!

Regards

Pali

PS: hope to see you in Enschede

**Comment by TheBnl** [comment]
Hi @silverstripesk 

I've implemented a draft of this feature on the 1.x branch (ss3) i've not had the chance to test it out yet though. But i've you'd like you could try it by requiring "1.x-dev" in your composer file 👍 

I'll probably get to testing myself somewhere next week!

**Comment by TheBnl** [comment]
I've tested and the required cookie groups are now configurable!
You can configure this by setting the `required_groups` config array on the `Broarm\CookieConsent\CookieConsent` class. Make sure you use the same name as used under the `cookies` array.

This would make all configured groups required:
```yml
Broarm\CookieConsent\CookieConsent:
  required_groups:
    - Necessary
    - Analytics
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    Analytics:
      local:
        - _ga
        - _gat
        - _gid
```
